### ISSUE TITLE
Uninitialized constant Bullet::Mongoid on Rails 4.2.

### ISSUE THREAD

**Issue by phyllisstein** [flyerhzm/bullet#222]
Hey there! This may be a duplicate of #185, but I'm seeing an uninitialized constant error on Rails 4.2.0, 4.2.1, and 4.2.2.beta, with Mongoid 4.0.0 and 4.0.2. Here's the backtrace:

```
/usr/local/rvm/gems/ruby-2.2.1@ignota-rupertsberg/gems/bullet-4.14.4/lib/bullet.rb:48:in `enable=': uninitialized constant Bullet::Mongoid (NameError)
	from /Users/danielsh/Repos/Ignota/Rupertsberg/config/environments/development.rb:56:in `block (2 levels) in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.1@ignota-rupertsberg/bundler/gems/rails-4df216cb12e3/activesupport/lib/active_support/lazy_load_hooks.rb:36:in `call'
	from /usr/local/rvm/gems/ruby-2.2.1@ignota-rupertsberg/bundler/gems/rails-4df216cb12e3/activesupport/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /usr/local/rvm/gems/ruby-2.2.1@ignota-rupertsberg/bundler/gems/rails-4df216cb12e3/activesupport/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /usr/local/rvm/gems/ruby-2.2.1@ignota-rupertsberg/bundler/gems/rails-4df216cb12e3/activesupport/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /usr/local/rvm/gems/ruby-2.2.1@ignota-rupertsberg/bundler/gems/rails-4df216cb12e3/activesupport/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /usr/local/rvm/gems/ruby-2.2.1@ignota-rupertsberg/bundler/gems/rails-4df216cb12e3/railties/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
	from /usr/local/rvm/gems/ruby-2.2.1@ignota-rupertsberg/bundler/gems/rails-4df216cb12e3/railties/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/rvm/gems/ruby-2.2.1@ignota-rupertsberg/bundler/gems/rails-4df216cb12e3/railties/lib/rails/initializable.rb:30:in `run'
	from /usr/local/rvm/gems/ruby-2.2.1@ignota-rupertsberg/bundler/gems/rails-4df216cb12e3/railties/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /usr/local/rvm/gems/ruby-2.2.1@ignota-rupertsberg/bundler/gems/rails-4df216cb12e3/railties/lib/rails/initializable.rb:54:in `run_initializers'
	from /usr/local/rvm/gems/ruby-2.2.1@ignota-rupertsberg/bundler/gems/rails-4df216cb12e3/railties/lib/rails/application.rb:352:in `initialize!'
	from /Users/danielsh/Repos/Ignota/Rupertsberg/config/environment.rb:8:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.1@ignota-rupertsberg/gems/spring-1.3.4/lib/spring/application.rb:92:in `require'
	from /usr/local/rvm/gems/ruby-2.2.1@ignota-rupertsberg/gems/spring-1.3.4/lib/spring/application.rb:92:in `preload'
	from /usr/local/rvm/gems/ruby-2.2.1@ignota-rupertsberg/gems/spring-1.3.4/lib/spring/application.rb:143:in `serve'
	from /usr/local/rvm/gems/ruby-2.2.1@ignota-rupertsberg/gems/spring-1.3.4/lib/spring/application.rb:131:in `block in run'
	from /usr/local/rvm/gems/ruby-2.2.1@ignota-rupertsberg/gems/spring-1.3.4/lib/spring/application.rb:125:in `loop'
	from /usr/local/rvm/gems/ruby-2.2.1@ignota-rupertsberg/gems/spring-1.3.4/lib/spring/application.rb:125:in `run'
	from /usr/local/rvm/gems/ruby-2.2.1@ignota-rupertsberg/gems/spring-1.3.4/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

Right now my `development.rb` just has this in it:

```ruby
config.after_initialize do
  Bullet.enable = true
end
```

If it'd be useful, you can check out the problem repo at <https://github.com/ignota/rupertsberg/tree/develop>. I can't spot anything else in the Gemfile or configuration that would be causing this particular exception, but I could easily be missing something. Thanks in advance for any insight you can provide!

**Comment by flyerhzm** [comment]
@phyllisstein  I tried rails 4.2.2 and mongoid 4.0.2, didn't get such error.

**Comment by halilim** [comment]
Note that this can happen if `mongoid` comes *after* `bullet` in the `Gemfile`. Moving `mongoid` to a higher position than `bullet` has fixed it for me (I didn't have to move it to the first line unlike [this SO answer](http://stackoverflow.com/a/22278004/372654), though it might depend on the other gems in the file).

**Comment by phyllisstein** [comment]
@halilim Thank you so much for that pointer! I'd always assumed the `Gemfile` order thing was, at bottom, superstition, but rearranging the two gems sorted the issue right the heck out. I'm forever grateful.

**Comment by halilim** [comment]
I'm glad it was helpful :)
