### ISSUE TITLE
False positive with belongs_to -> belongs_to

### ISSUE THREAD

**Issue by printercu** [flyerhzm/bullet#224]
Hi!

Seems like there false warnings for chain of belongs_to -> belongs_to relation, like this

```ruby
Bullet.profile { ProjectVersion.first.project.manager }; Bullet.warnings
# N+1 Query detected
#   App => [:manager]
#   Add to your finder: :includes => [:manager]
```
There are 3 queries anyway: with `includes(project: :manager)` or without. Is there any way to disable warnings if there were the only query for each relation?

Thanks!

rails 4.2.1, bullet 4.14.4

**Comment by tirdadc** [comment]
Just ran into this with a simple belongs_to setup.

**Comment by flyerhzm** [comment]
@printercu @tirdadc I have fixed on master branch, please try and let me know if it works for you

**Comment by printercu** [comment]
Can't load my fixtures :( 
```
Exception: NoMethodError: undefined method `include?' for nil:NilClass
--
0: gems/ruby-2.2.1/bundler/gems/bullet-9fc6e7ffd65f/lib/bullet/detector/n_plus_one_query.rb:62:in `impossible?'
1: gems/ruby-2.2.1/bundler/gems/bullet-9fc6e7ffd65f/lib/bullet/active_record42.rb:140:in `reader'
2: gems/ruby-2.2.1/gems/activerecord-4.2.1/lib/active_record/associations/builder/association.rb:115:in `user'
3: gems/ruby-2.2.1/gems/activemodel-4.2.1/lib/active_model/validator.rb:149:in `block in validate'
4: gems/ruby-2.2.1/gems/activemodel-4.2.1/lib/active_model/validator.rb:148:in `each'
```

**Comment by flyerhzm** [comment]
@printercu already fixed, please update and try again

**Comment by printercu** [comment]
Works for me, thanks!
