### ISSUE TITLE
4.14.6 breaks my app

### ISSUE THREAD

**Issue by dankohn** [flyerhzm/bullet#231]
I'm running a large Rails 4.2.1 app. bullet 4.14.5 works fine. With 4.14.6, my Cucumber tests give dozens of errors like:
```
cu features/tasks.feature:18
Using the default profile...
......F-

(::) failed steps (::)

undefined method `id' for nil:NilClass (ActionView::Template::Error)
./app/views/admin/claim_notes/tasks.html.slim:43:in `block in _app_views_admin_claim_notes_tasks_html_slim__1688958936765702605_70110320497080'
./app/views/admin/claim_notes/tasks.html.slim:37:in `_app_views_admin_claim_notes_tasks_html_slim__1688958936765702605_70110320497080'
./app/controllers/application_controller.rb:76:in `use_zone'
features/tasks.feature:18:in `Then I should see only the task assigned to the second user'

Failing Scenarios:
cucumber features/tasks.feature:15 # Scenario: Filter for another user who has one tasks

1 scenario (1 failed)
8 steps (1 failed, 1 skipped, 6 passed)
0m25.107s
```
The errors are always `undefined method `id' for nil:NilClass`. I'm happy to try a bullet branch if it would help you debug the problem.

**Comment by amplicity** [comment]
Getting the same issue @dankohn in a very large rails 4.2.1 app running ruby 2.2.2

**Comment by deniskorobicyn** [comment]
Same here...

**Comment by flyerhzm** [comment]
@dankohn @amplicity I fixed on master branch, please try and let me know if it works

**Comment by amplicity** [comment]
haven't checked yet, will do an update and let you know

**Comment by dankohn** [comment]
Yes, the commit on master fixes the bug. Thanks.

**Comment by dankohn** [comment]
Actually, the latest commit causes this new error (thanks to @ivanoblomov):
```
rs spec/models/user_spec.rb:6
/Users/oblomov/.rvm/gems/ruby-2.2.2/bundler/gems/bullet-3eb5c82edc42/lib/bullet.rb:32:in `singleton class': uninitialized constant UniformNotifier::AVAILABLE_NOTIFIERS (NameError)
	from /Users/oblomov/.rvm/gems/ruby-2.2.2/bundler/gems/bullet-3eb5c82edc42/lib/bullet.rb:27:in `<module:Bullet>'
	from /Users/oblomov/.rvm/gems/ruby-2.2.2/bundler/gems/bullet-3eb5c82edc42/lib/bullet.rb:8:in `<top (required)>'
	from /Users/oblomov/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in `require'
	from /Users/oblomov/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/oblomov/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in `each'
	from /Users/oblomov/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/oblomov/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in `each'
	from /Users/oblomov/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in `require'
	from /Users/oblomov/.rvm/gems/ruby-2.2.2@global/gems/bundler-1.9.4/lib/bundler.rb:134:in `require'
	from /Users/oblomov/Documents/code/chewy/config/application.rb:7:in `<top (required)>'
	from /Users/oblomov/.rvm/gems/ruby-2.2.2/gems/spring-1.3.5/lib/spring/application.rb:82:in `require'
	from /Users/oblomov/.rvm/gems/ruby-2.2.2/gems/spring-1.3.5/lib/spring/application.rb:82:in `preload'
	from /Users/oblomov/.rvm/gems/ruby-2.2.2/gems/spring-1.3.5/lib/spring/application.rb:143:in `serve'
	from /Users/oblomov/.rvm/gems/ruby-2.2.2/gems/spring-1.3.5/lib/spring/application.rb:131:in `block in run'
	from /Users/oblomov/.rvm/gems/ruby-2.2.2/gems/spring-1.3.5/lib/spring/application.rb:125:in `loop'
	from /Users/oblomov/.rvm/gems/ruby-2.2.2/gems/spring-1.3.5/lib/spring/application.rb:125:in `run'
	from /Users/oblomov/.rvm/gems/ruby-2.2.2/gems/spring-1.3.5/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/oblomov/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/oblomov/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by flyerhzm** [comment]
@dankohn I didn't see such error, did you get uniform_notifier 1.9.0 installed?
