### ISSUE TITLE
Error raised for Mongoid 5.0.0

### ISSUE THREAD

**Issue by PikachuEXE** [flyerhzm/bullet#253]
## Error
```
/Users/PikachuEXE/.rvm/gems/ruby-2.2.3/gems/bullet-4.14.7/lib/bullet.rb:50:in `enable=': cannot load such file -- bullet/ (LoadError)
	from /Users/PikachuEXE/Projects/spacious/spacious-rails/config/initializers/bullet.rb:2:in `<top (required)>'
```

## Code
```ruby
Bullet.enable = true
```

**Comment by PikachuEXE** [comment]
It seems master is fine with `mongoid` `5.0.0`
I guess I will wait for new version to be released
