### ISSUE TITLE
Rails 5, @child.parent, N+1 bullet. Maybe a bug?

### ISSUE THREAD

**Issue by ghost** [flyerhzm/bullet#308]
Rails 5.

New app, all default.

Bullet gem tell me this:

```
user: root
/children/2
N+1 Query detected
  Child => [:parent]
  Add to your finder: :includes => [:parent]
N+1 Query method call stack
  app/controllers/children_controller.rb:14:in `show'
app/controllers/children_controller.rb:14:in `show'
```

I have these **models**:

```
class Parent < ApplicationRecord

    has_many :children

end

class Child < ApplicationRecord

    belongs_to :parent

end
```

I have this controller in **children_controller.rb** with:

```
...

def show
    @parent = @child.parent
end
...
```

In my views **views/children/show.html.erb** I have this:

```
...
<%= @parent.name %>
...
```

If I invert this and in view I put:

```
<%= @child.parent.name %>
```

and in controller:

```
...

def show
    #nothing more
end
...
```

I have the same error from Bullet but in html.

**How to fix this? Is really a N+1 problem or Bullet is wrong?**

The project is really really new. First models.

**Comment by flyerhzm** [comment]
@johnunclesam could you build a demo app which can help me reproduce this issue?

**Comment by johnunclesam** [comment]
I can't right now. But simple make a new app with `rails new app` et voilà! The new app with those models.

But the question is: Is N+1 this? `@parent = @child.parent`

With Rails 4 I remember not. It's simply a bug?

**Comment by sauy7** [comment]
Demo app: https://github.com/sauy7/bullet_308

This is 1+1. You still get 2 queries when you could have one. In children_controller.rb:

```
def show
  @child = Child.includes(:parent).find(params[:id])
end
```

makes the warning go away.

**Comment by mrkongo** [comment]
But this is the right way? I need to show how many children are in my Parent index action in controller.

**Comment by sauy7** [comment]
@mrkongo Not sure I understand what you mean. This issue was about N+1 in the ChildrenController#show action. Now you're talking about ParentsController#index?

**Comment by mrkongo** [comment]
Yes, I did not understand question very well. Sorry. What do you think of this: https://rossta.net/blog/n+1-is-a-rails-feature.html ?

**Comment by sauy7** [comment]
@mrkongo It seems like a very reasonable discussion about the different options we have in Rails for dealing with N+1 queries. In short, like much in programming, what solution to use depends on project requirements.

**Comment by flyerhzm** [comment]
do you have a chance to try bullet 5.4.3?
