### ISSUE TITLE
cannot load such file -- bullet/ (LoadError)

### ISSUE THREAD

**Issue by shime** [flyerhzm/bullet#310]
```ruby
# Gemfile
group :development, :test do
  gem 'bullet'
end
```

```ruby
# config/evironments/development.rb
config.after_initialize do
  Bullet.enable = true
  Bullet.bullet_logger = true
  Bullet.rails_logger = true
end
```

After trying to start the server with `rails s` I'm getting this:

<details>
```
=> Booting Passenger application server
=> Rails 5.0.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
/Users/hrvoje/.gem/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- bullet/ (LoadError)
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/bullet-4.14.7/lib/bullet.rb:51:in `enable='
	from /Users/hrvoje/code/work/foo/config/environments/development.rb:64:in `block (2 levels) in <top (required)>'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/application/finisher.rb:65:in `block in <module:Finisher>'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `run'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/hrvoje/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/hrvoje/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/hrvoje/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/hrvoje/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/hrvoje/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/hrvoje/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/hrvoje/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/hrvoje/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/hrvoje/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/application.rb:352:in `initialize!'
	from /Users/hrvoje/code/work/foo/config/environment.rb:17:in `<top (required)>'
	from /Users/hrvoje/code/work/foo/config.ru:3:in `require_relative'
	from /Users/hrvoje/code/work/foo/config.ru:3:in `block in <main>'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
	from /Users/hrvoje/code/work/foo/config.ru:in `new'
	from /Users/hrvoje/code/work/foo/config.ru:in `<main>'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/server.rb:59:in `app'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/server.rb:124:in `log_to_stdout'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/server.rb:77:in `start'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/hrvoje/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'
Exiting
```
</details>

Ruby 2.3.0p0
Rails 5.0.0

**Comment by shime** [comment]
Weird. It seems that bundler installed version `4.14.7` by default, fixed after specifying the version explicitly in the Gemfile to be `5.4.0`.

**Comment by lucis-fluxum** [comment]
Bundler installed the correct version (5.4.0) for me, but I'm still getting this error.
(Using Ruby 2.3.1)

```ruby
# Gemfile
gem 'rails', '5.0.0.1'
gem 'mongoid', '6.0.0'

...

group :development do
  gem 'bullet', '5.4.0'
end
```

```ruby
# config/evironments/development.rb
config.after_initialize do
  Bullet.enable = true
  Bullet.bullet_logger = true
  Bullet.rails_logger = true
end
```

On running `rails server`:
<details>
```
=> Booting Puma
=> Rails 5.0.0.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
/home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- bullet/ (LoadError)
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bullet-5.4.0/lib/bullet.rb:54:in `enable='
        from /home/luc/Desktop/Development/Ruby/mongoid-sandbox/config/environments/development.rb:53:in `block (2 levels) in <top (required)>'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:44:in `each'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application/finisher.rb:65:in `block in <module:Finisher>'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `run'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:352:in `initialize!'
        from /home/luc/Desktop/Development/Ruby/mongoid-sandbox/config/environment.rb:5:in `<top (required)>'
        from /home/luc/Desktop/Development/Ruby/mongoid-sandbox/config.ru:3:in `require_relative'
        from /home/luc/Desktop/Development/Ruby/mongoid-sandbox/config.ru:3:in `block in <main>'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
        from /home/luc/Desktop/Development/Ruby/mongoid-sandbox/config.ru:in `new'
        from /home/luc/Desktop/Development/Ruby/mongoid-sandbox/config.ru:in `<main>'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/server.rb:59:in `app'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/server.rb:124:in `log_to_stdout'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/server.rb:77:in `start'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:90:in `block in server'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
        from /home/luc/Desktop/Development/Ruby/mongoid-sandbox/bin/rails:9:in `require'
        from /home/luc/Desktop/Development/Ruby/mongoid-sandbox/bin/rails:9:in `<top (required)>'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `load'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `call'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/client/command.rb:7:in `call'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/client.rb:30:in `run'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/bin/spring:49:in `<top (required)>'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `load'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `<top (required)>'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/luc/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/luc/Desktop/Development/Ruby/mongoid-sandbox/bin/spring:13:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'
```
</details>

**Comment by flyerhzm** [comment]
@lucis-fluxum this is because bullet does not support mongoid 6 yet.
