### ISSUE TITLE
belongs_to association fails to load in Rails 5.1 when bullet is enabled.

### ISSUE THREAD

**Issue by mohitnatoo** [flyerhzm/bullet#327]
Error shown is as follows

```
ArgumentError: wrong number of arguments (given 1, expected 0)
/Users/mohitnatoo/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.0.beta1/lib/active_record/associations/singular_association.rb:5:in `reader'
/Users/mohitnatoo/.rvm/gems/ruby-2.3.1/gems/bullet-5.5.0/lib/bullet/active_record5.rb:207:in `reader'
/Users/mohitnatoo/.rvm/gems/ruby-2.3.1/gems/activerecord-5.1.0.beta1/lib/active_record/associations/builder/association.rb:111:in `user'
/Users/mohitnatoo/.rvm/gems/ruby-2.3.1/gems/activemodel-5.1.0.beta1/lib/active_model/validator.rb:148:in `block in validate'
/Users/mohitnatoo/.rvm/gems/ruby-2.3.1/gems/activemodel-5.1.0.beta1/lib/active_model/validator.rb:147:in `each'
/Users/mohitnatoo/.rvm/gems/ruby-2.3.1/gems/activemodel-5.1.0.beta1/lib/active_model/validator.rb:147:in `validate'
```

Example use case

I have a model `Task`, which belongs to `Project`

```
> Task.first.project

ArgumentError: wrong number of arguments (given 1, expected 0)
```

The above statement runs fine after disabling bullet gem.

**Comment by joshuapaling** [comment]
This is fixed in version 5.5.1 - see https://github.com/flyerhzm/bullet/commit/eb091c1afc81c7834e8d2a07d2429a61936854f7

**Comment by eduardo-lago-aguilar** [comment]
Using bullet version 5.5.1 works for me!

**Comment by olingern** [comment]
For those who come here, we saw this error using bullet version 5.6.1 on Rails 5.1.4.

Bumping to version 5.7.5 resolved this for us.

**Comment by gracezhangyaofei** [comment]
Hi version `5.7.5` or `5.5.1` or `5.6.1`, none of them work for me now.
Rails `5.1.0`, mongoid `6.4.1`, anyone got any clue? Is it because mongoid version too high? Quite urgent. Many thanks!
