### ISSUE TITLE
On Mongoid 6 & Rails 5, Bullet does not seem to be working fine

### ISSUE THREAD

**Issue by cheenu** [flyerhzm/bullet#331]
Without Bullet, these are the logs

```
Started GET "/beds?property_id=58dcdcb1a0b3cd756226bf4a" for ::1 at 2017-04-04 16:16:24 +0530
Processing by BedsController#index as HTML
  Parameters: {"property_id"=>"58dcdcb1a0b3cd756226bf4a"}
MONGODB | localhost:27017 | sidekick_development.find | STARTED | {"find"=>"accounts", "filter"=>{"deleted_at"=>nil, "_id"=>BSON::ObjectId('58dcdcb1a0b3cd756226bf44')}}
MONGODB | localhost:27017 | sidekick_development.find | SUCCEEDED | 0.00051s
MONGODB | localhost:27017 | sidekick_development.find | STARTED | {"find"=>"properties", "filter"=>{"deleted_at"=>nil, "account_id"=>BSON::ObjectId('58dcdcb1a0b3cd756226bf44'), "_id"=>BSON::ObjectId('58dcdcb1a0b3cd756226bf4a')}}
MONGODB | localhost:27017 | sidekick_development.find | SUCCEEDED | 0.0006659999999999999s
MONGODB | localhost:27017 | sidekick_development.find | STARTED | {"find"=>"beds", "filter"=>{"deleted_at"=>nil, "property_id"=>BSON::ObjectId('58dcdcb1a0b3cd756226bf4a'), "disabled"=>false}}
MONGODB | localhost:27017 | sidekick_development.find | SUCCEEDED | 0.003728s
MONGODB | localhost:27017 | sidekick_development.getMore | STARTED | {"getMore"=>393648371413, "collection"=>"beds"}
MONGODB | localhost:27017 | sidekick_development.getMore | SUCCEEDED | 0.001922s
MONGODB | localhost:27017 | sidekick_development.find | STARTED | {"find"=>"rooms", "filter"=>{"deleted_at"=>nil, "_id"=>{"$in"=>[BSON::ObjectId('58dcdcb2a0b3cd756226bf79'), BSON::ObjectId('58dcdcb2a0b3cd756226bf7c'), BSON::ObjectId('58dcdcb2a0b3cd756226bf7e'), BSON::ObjectId('58dcdcb3a0b3cd756226bf83'), BSON::Objec...
MONGODB | localhost:27017 | sidekick_development.find | SUCCEEDED | 0.0018490000000000002s
MONGODB | localhost:27017 | sidekick_development.find | STARTED | {"find"=>"bed_types", "filter"=>{"deleted_at"=>nil, "_id"=>{"$in"=>[BSON::ObjectId('58dcdcb1a0b3cd756226bf4e'), BSON::ObjectId('58dcdcb1a0b3cd756226bf4c'), BSON::ObjectId('58dcdcb1a0b3cd756226bf4f'), BSON::ObjectId('58dcdcb1a0b3cd756226bf4b')]}}}
MONGODB | localhost:27017 | sidekick_development.find | SUCCEEDED | 0.0006020000000000001s
MONGODB | localhost:27017 | sidekick_development.find | STARTED | {"find"=>"bed_statuses", "filter"=>{"deleted_at"=>nil, "_id"=>{"$in"=>[BSON::ObjectId('58dcdcb2a0b3cd756226bf6a')]}}}
MONGODB | localhost:27017 | sidekick_development.find | SUCCEEDED | 0.000638s
MONGODB | localhost:27017 | sidekick_development.find | STARTED | {"find"=>"bed_custom_fields", "filter"=>{"deleted_at"=>nil, "bed_id"=>{"$in"=>[BSON::ObjectId('58dcdcb2a0b3cd756226bf7a'), BSON::ObjectId('58dcdcb2a0b3cd756226bf7b'), BSON::ObjectId('58dcdcb2a0b3cd756226bf7d'), BSON::ObjectId('58dcdcb2a0b3cd756226bf7f...
MONGODB | localhost:27017 | sidekick_development.find | SUCCEEDED | 0.00115s
Completed 200 OK in 283ms (Views: 218.8ms)
```

Clearly no N+1 Queries

However, upon enabling Bullet

```
Started GET "/beds?property_id=58dcdcb1a0b3cd756226bf4a" for ::1 at 2017-04-04 16:17:50 +0530
Processing by BedsController#index as HTML
  Parameters: {"property_id"=>"58dcdcb1a0b3cd756226bf4a"}
MONGODB | Topology type 'unknown' initializing.
MONGODB | Server localhost:27017 initializing.
MONGODB | Topology type 'unknown' changed to type 'single'.
MONGODB | Server description for localhost:27017 changed from 'unknown' to 'standalone'.
MONGODB | There was a change in the members of the 'single' topology.
MONGODB | localhost:27017 | sidekick_development.find | STARTED | {"find"=>"accounts", "filter"=>{"deleted_at"=>nil, "_id"=>BSON::ObjectId('58dcdcb1a0b3cd756226bf44')}}
MONGODB | localhost:27017 | sidekick_development.find | SUCCEEDED | 0.0012490000000000001s
MONGODB | localhost:27017 | sidekick_development.find | STARTED | {"find"=>"accounts", "filter"=>{"deleted_at"=>nil, "_id"=>BSON::ObjectId('58dcdcb1a0b3cd756226bf44')}}
MONGODB | localhost:27017 | sidekick_development.find | SUCCEEDED | 0.000774s
MONGODB | localhost:27017 | sidekick_development.find | STARTED | {"find"=>"properties", "filter"=>{"deleted_at"=>nil, "account_id"=>BSON::ObjectId('58dcdcb1a0b3cd756226bf44'), "_id"=>BSON::ObjectId('58dcdcb1a0b3cd756226bf4a')}}
MONGODB | localhost:27017 | sidekick_development.find | SUCCEEDED | 0.000984s
MONGODB | localhost:27017 | sidekick_development.find | STARTED | {"find"=>"properties", "filter"=>{"deleted_at"=>nil, "account_id"=>BSON::ObjectId('58dcdcb1a0b3cd756226bf44'), "_id"=>BSON::ObjectId('58dcdcb1a0b3cd756226bf4a')}}
MONGODB | localhost:27017 | sidekick_development.find | SUCCEEDED | 0.000777s
MONGODB | localhost:27017 | sidekick_development.find | STARTED | {"find"=>"beds", "filter"=>{"deleted_at"=>nil, "property_id"=>BSON::ObjectId('58dcdcb1a0b3cd756226bf4a'), "disabled"=>false}}
MONGODB | localhost:27017 | sidekick_development.find | SUCCEEDED | 0.0038510000000000003s
MONGODB | localhost:27017 | sidekick_development.getMore | STARTED | {"getMore"=>391530167835, "collection"=>"beds"}
MONGODB | localhost:27017 | sidekick_development.getMore | SUCCEEDED | 0.002277s
MONGODB | localhost:27017 | sidekick_development.find | STARTED | {"find"=>"beds", "filter"=>{"deleted_at"=>nil, "property_id"=>BSON::ObjectId('58dcdcb1a0b3cd756226bf4a'), "disabled"=>false}}
MONGODB | localhost:27017 | sidekick_development.find | SUCCEEDED | 0.003462s
MONGODB | localhost:27017 | sidekick_development.getMore | STARTED | {"getMore"=>392529797251, "collection"=>"beds"}
MONGODB | localhost:27017 | sidekick_development.getMore | SUCCEEDED | 0.0021049999999999997s
MONGODB | localhost:27017 | sidekick_development.find | STARTED | {"find"=>"rooms", "filter"=>{"deleted_at"=>nil, "_id"=>{"$in"=>[BSON::ObjectId('58dcdcb2a0b3cd756226bf79'), BSON::ObjectId('58dcdcb2a0b3cd756226bf7c'), BSON::ObjectId('58dcdcb2a0b3cd756226bf7e'), BSON::ObjectId('58dcdcb3a0b3cd756226bf83'), BSON::Objec...
MONGODB | localhost:27017 | sidekick_development.find | SUCCEEDED | 0.0013039999999999998s
MONGODB | localhost:27017 | sidekick_development.find | STARTED | {"find"=>"rooms", "filter"=>{"deleted_at"=>nil, "_id"=>{"$in"=>[BSON::ObjectId('58dcdcb2a0b3cd756226bf79'), BSON::ObjectId('58dcdcb2a0b3cd756226bf7c'), BSON::ObjectId('58dcdcb2a0b3cd756226bf7e'), BSON::ObjectId('58dcdcb3a0b3cd756226bf83'), BSON::Objec...
MONGODB | localhost:27017 | sidekick_development.find | SUCCEEDED | 0.001095s
MONGODB | localhost:27017 | sidekick_development.find | STARTED | {"find"=>"bed_types", "filter"=>{"deleted_at"=>nil, "_id"=>{"$in"=>[BSON::ObjectId('58dcdcb1a0b3cd756226bf4e'), BSON::ObjectId('58dcdcb1a0b3cd756226bf4c'), BSON::ObjectId('58dcdcb1a0b3cd756226bf4f'), BSON::ObjectId('58dcdcb1a0b3cd756226bf4b')]}}}
MONGODB | localhost:27017 | sidekick_development.find | SUCCEEDED | 0.000759s
MONGODB | localhost:27017 | sidekick_development.find | STARTED | {"find"=>"bed_types", "filter"=>{"deleted_at"=>nil, "_id"=>{"$in"=>[BSON::ObjectId('58dcdcb1a0b3cd756226bf4e'), BSON::ObjectId('58dcdcb1a0b3cd756226bf4c'), BSON::ObjectId('58dcdcb1a0b3cd756226bf4f'), BSON::ObjectId('58dcdcb1a0b3cd756226bf4b')]}}}
MONGODB | localhost:27017 | sidekick_development.find | SUCCEEDED | 0.0006389999999999999s
MONGODB | localhost:27017 | sidekick_development.find | STARTED | {"find"=>"bed_statuses", "filter"=>{"deleted_at"=>nil, "_id"=>{"$in"=>[BSON::ObjectId('58dcdcb2a0b3cd756226bf6a')]}}}
MONGODB | localhost:27017 | sidekick_development.find | SUCCEEDED | 0.000655s
MONGODB | localhost:27017 | sidekick_development.find | STARTED | {"find"=>"bed_statuses", "filter"=>{"deleted_at"=>nil, "_id"=>{"$in"=>[BSON::ObjectId('58dcdcb2a0b3cd756226bf6a')]}}}
MONGODB | localhost:27017 | sidekick_development.find | SUCCEEDED | 0.0006770000000000001s
MONGODB | localhost:27017 | sidekick_development.find | STARTED | {"find"=>"bed_custom_fields", "filter"=>{"deleted_at"=>nil, "bed_id"=>{"$in"=>[BSON::ObjectId('58dcdcb2a0b3cd756226bf7a'), BSON::ObjectId('58dcdcb2a0b3cd756226bf7b'), BSON::ObjectId('58dcdcb2a0b3cd756226bf7d'), BSON::ObjectId('58dcdcb2a0b3cd756226bf7f...
MONGODB | localhost:27017 | sidekick_development.find | SUCCEEDED | 0.000946s
MONGODB | localhost:27017 | sidekick_development.find | STARTED | {"find"=>"bed_custom_fields", "filter"=>{"deleted_at"=>nil, "bed_id"=>{"$in"=>[BSON::ObjectId('58dcdcb2a0b3cd756226bf7a'), BSON::ObjectId('58dcdcb2a0b3cd756226bf7b'), BSON::ObjectId('58dcdcb2a0b3cd756226bf7d'), BSON::ObjectId('58dcdcb2a0b3cd756226bf7f...
MONGODB | localhost:27017 | sidekick_development.find | SUCCEEDED | 0.0008690000000000001s
Completed 200 OK in 806ms (Views: 705.4ms)


user: clinchpad
GET /beds?property_id=58dcdcb1a0b3cd756226bf4a
USE eager loading detected
  Bed => [:room]
  Add to your finder: :includes => [:room]
Call stack
  /Users/clinchpad/sidekickhms/api/app/controllers/beds_controller.rb:171:in `index'


user: clinchpad
GET /beds?property_id=58dcdcb1a0b3cd756226bf4a
USE eager loading detected
  Bed => [:bed_type]
  Add to your finder: :includes => [:bed_type]
Call stack
  /Users/clinchpad/sidekickhms/api/app/controllers/beds_controller.rb:171:in `index'


user: clinchpad
GET /beds?property_id=58dcdcb1a0b3cd756226bf4a
USE eager loading detected
  Bed => [:bed_status]
  Add to your finder: :includes => [:bed_status]
Call stack
  /Users/clinchpad/sidekickhms/api/app/controllers/beds_controller.rb:171:in `index'


user: clinchpad
GET /beds?property_id=58dcdcb1a0b3cd756226bf4a
USE eager loading detected
  Bed => [:bed_custom_fields]
  Add to your finder: :includes => [:bed_custom_fields]
Call stack
  /Users/clinchpad/sidekickhms/api/app/controllers/beds_controller.rb:171:in `index'
```

Queries are executed twice and N+1 Query is triggered. 

Am I missing something or is Bullet not configured to work with Mongoid 6/Rails 5?

I'm using v 5.5.1 of Bullet

**Comment by flyerhzm** [comment]
I didn't use mongoid 6 for any project yet.

**Comment by exocode** [comment]
yes, I can confirm that! Mongoid 6.1.0

**Comment by thomasleese** [comment]
I'm experiencing this same problem on a different project, were you able to do any further investigation here and find out what the problem was?
