### ISSUE TITLE
Bullet 5.4.2 compatibility with Rails 5.1.2

### ISSUE THREAD

**Issue by mingshenggan** [flyerhzm/bullet#343]
While performing an upgrade to Rails 5.1.2, I am finding that `bullet 5.4.2` is incompatible with rails 5 (activerecord). Will not be prying deeper though for the time being.

Works well with `Bullet 5.5.1`

Nevertheless, is this the right place to report to? Or should I be reporting to bundler?

```
Development [1] project(main)> FactoryGirl.create(:country)
   (0.3ms)  BEGIN
   (0.3ms)  ROLLBACK
ArgumentError: wrong number of arguments (given 1, expected 0)
from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.2/lib/active_record/associations/singular_association.rb:5:in `reader'
Development [2] project(main)>
Development [2] project(main)> exit
project [ rails c                                                                        update-to-rails-5 * ] 9:15 AM
Running via Spring preloader in process 12650
Loading development environment (Rails 5.1.2)

Frame number: 0/24
Development [1] project(main)> FactoryGirl.create(:country)
   (0.2ms)  BEGIN
   (0.3ms)  ROLLBACK
ActiveRecord::RecordInvalid: Validation failed: Scope must exist
from /usr/local/opt/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activerecord-5.1.2/lib/active_record/validations.rb:78:in `raise_validation_error'
Development [2] project(main)>
```

**Comment by flyerhzm** [comment]
@mingsheng88 yes, we have a fix for this https://github.com/flyerhzm/bullet/commit/bcb7b69b004f44da706cb953587297a9d4fb6357

**Comment by mingsheng88** [comment]
should this be reported to bundler so that the dependency is updated?
