### ISSUE TITLE
Bullet is not compatible with Rails 5.2 

### ISSUE THREAD

**Issue by Yanchek99** [flyerhzm/bullet#369]
Gemfile
```
gem 'rails', '5.2.0.beta1'
gem 'bullet', '2.0.0.rc1'
```

Error when running `rails s`

```
/.rvm/gems/ruby-2.4.2@test/gems/bullet-2.0.0.rc1/lib/bullet/active_record2.rb:7:in `alias_method': undefined method `find_every' for class `#<Class:ActiveRecord::Base>' (NameError)

from /.rvm/gems/ruby-2.4.2@test/gems/bullet-2.0.0.rc1/lib/bullet/active_record2.rb:7:in `singleton class'

from /.rvm/gems/ruby-2.4.2@test/gems/bullet-2.0.0.rc1/lib/bullet/active_record2.rb:6:in `block in enable'

from /.rvm/gems/ruby-2.4.2@test/gems/bullet-2.0.0.rc1/lib/bullet/active_record2.rb:5:in `class_eval'

from /.rvm/gems/ruby-2.4.2@test/gems/bullet-2.0.0.rc1/lib/bullet/active_record2.rb:5:in `enable'

from /.rvm/gems/ruby-2.4.2@test/gems/bullet-2.0.0.rc1/lib/bullet.rb:47:in `enable='

from /Repositories/GitHub/test/config/environments/development.rb:62:in `block (2 levels) in <main>'

from /.rvm/gems/ruby-2.4.2@test/gems/activesupport-5.2.0.beta1/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'

from /.rvm/gems/ruby-2.4.2@test/gems/activesupport-5.2.0.beta1/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'

from /.rvm/gems/ruby-2.4.2@test/gems/activesupport-5.2.0.beta1/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'

from /.rvm/gems/ruby-2.4.2@test/gems/activesupport-5.2.0.beta1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'

from /.rvm/gems/ruby-2.4.2@test/gems/activesupport-5.2.0.beta1/lib/active_support/lazy_load_hooks.rb:51:in `each'

from /.rvm/gems/ruby-2.4.2@test/gems/activesupport-5.2.0.beta1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'

from /.rvm/gems/ruby-2.4.2@test/gems/railties-5.2.0.beta1/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'

from /.rvm/gems/ruby-2.4.2@test/gems/railties-5.2.0.beta1/lib/rails/initializable.rb:32:in `instance_exec'

from /.rvm/gems/ruby-2.4.2@test/gems/railties-5.2.0.beta1/lib/rails/initializable.rb:32:in `run'

from /.rvm/gems/ruby-2.4.2@test/gems/railties-5.2.0.beta1/lib/rails/initializable.rb:61:in `block in run_initializers'

from /.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'

from /.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'

from /.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'

from /.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'

from /.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `each'

from /.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `call'

from /.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'

from /.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'

from /.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'

from /.rvm/gems/ruby-2.4.2@test/gems/railties-5.2.0.beta1/lib/rails/initializable.rb:60:in `run_initializers'

from /.rvm/gems/ruby-2.4.2@test/gems/railties-5.2.0.beta1/lib/rails/application.rb:360:in `initialize!'

from /Repositories/GitHub/test/config/environment.rb:5:in `<main>'

from /.rvm/gems/ruby-2.4.2@test/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'

from /.rvm/gems/ruby-2.4.2@test/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'

from /.rvm/gems/ruby-2.4.2@test/gems/skylight-1.4.4/lib/skylight/probes.rb:81:in `require'

from /.rvm/gems/ruby-2.4.2@test/gems/activesupport-5.2.0.beta1/lib/active_support/dependencies.rb:283:in `block in require'

from /.rvm/gems/ruby-2.4.2@test/gems/activesupport-5.2.0.beta1/lib/active_support/dependencies.rb:249:in `load_dependency'

from /.rvm/gems/ruby-2.4.2@test/gems/activesupport-5.2.0.beta1/lib/active_support/dependencies.rb:283:in `require'

from config.ru:3:in `block in <main>'

from /.rvm/gems/ruby-2.4.2@test/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'

from /.rvm/gems/ruby-2.4.2@test/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'

from config.ru:in `new'

from config.ru:in `<main>'

from /.rvm/gems/ruby-2.4.2@test/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'

from /.rvm/gems/ruby-2.4.2@test/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'

from /.rvm/gems/ruby-2.4.2@test/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'

from /.rvm/gems/ruby-2.4.2@test/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'

from /.rvm/gems/ruby-2.4.2@test/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'

from /.rvm/gems/ruby-2.4.2@test/gems/railties-5.2.0.beta1/lib/rails/commands/server/server_command.rb:27:in `app'

from /.rvm/gems/ruby-2.4.2@test/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'

from /.rvm/gems/ruby-2.4.2@test/gems/railties-5.2.0.beta1/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'

from /.rvm/gems/ruby-2.4.2@test/gems/railties-5.2.0.beta1/lib/rails/commands/server/server_command.rb:51:in `start'

from /.rvm/gems/ruby-2.4.2@test/gems/railties-5.2.0.beta1/lib/rails/commands/server/server_command.rb:147:in `block in perform'

from /.rvm/gems/ruby-2.4.2@test/gems/railties-5.2.0.beta1/lib/rails/commands/server/server_command.rb:142:in `tap'

from /.rvm/gems/ruby-2.4.2@test/gems/railties-5.2.0.beta1/lib/rails/commands/server/server_command.rb:142:in `perform'

from /.rvm/gems/ruby-2.4.2@test/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'

from /.rvm/gems/ruby-2.4.2@test/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'

from /.rvm/gems/ruby-2.4.2@test/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'

from /.rvm/gems/ruby-2.4.2@test/gems/railties-5.2.0.beta1/lib/rails/command/base.rb:65:in `perform'

from /.rvm/gems/ruby-2.4.2@test/gems/railties-5.2.0.beta1/lib/rails/command.rb:46:in `invoke'

from /.rvm/gems/ruby-2.4.2@test/gems/railties-5.2.0.beta1/lib/rails/commands.rb:18:in `<main>'

from /.rvm/gems/ruby-2.4.2@test/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'

from /.rvm/gems/ruby-2.4.2@test/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'

from /.rvm/gems/ruby-2.4.2@test/gems/activesupport-5.2.0.beta1/lib/active_support/dependencies.rb:283:in `block in require'

from /.rvm/gems/ruby-2.4.2@test/gems/activesupport-5.2.0.beta1/lib/active_support/dependencies.rb:249:in `load_dependency'

from /.rvm/gems/ruby-2.4.2@test/gems/activesupport-5.2.0.beta1/lib/active_support/dependencies.rb:283:in `require'

from bin/rails:4:in `<main>'
```

**Comment by flyerhzm** [comment]
@Yanchek99 please upgrade bullet to 5.7.0
