### ISSUE TITLE
uninitialized constant Bullet::ActiveRecord

### ISSUE THREAD

**Issue by blanchma** [flyerhzm/bullet#396]
I have installed Active 5.1.5 and when I do Bullet.enable = true I get:

```
NameError: uninitialized constant Bullet::ActiveRecord
	from /Users/blanchma/.rvm/gems/ruby-2.3.1@concourse/gems/bullet-5.7.5/lib/bullet.rb:57:in `enable='
```
```
> Bullet.active_record?
 => "constant"
```
```
 > Bullet.active_record_version
 => "active_record5"
```

**Comment by blanchma** [comment]
Hey guys. Any help with this?

**Comment by blanchma** [comment]
`Bullet::ActiveRecord.enable if active_record?` is the failing one inside

**Comment by flyerhzm** [comment]
@blanchma I have tested it with rails 5.1.6 and ruby 2.4.3, I didn't see your issue, is it possible to create a public repo on github to reproduce the issue?

**Comment by wellington1993** [comment]
Needs require: true like:
gem 'bullet', require: true

at Gemfile or gem declaration?

Regards.

**Comment by flyerhzm** [comment]
anyone can help me reproduce it?

**Comment by dim0627** [comment]
I have same problem.

```
Rails 5.2.1
Ruby 2.5.3
Bullet 5.9.0
```

I just only using in rspec.

spec_helper.rb
``` ruby
  if Bullet.enable?
    config.before do
      Bullet.start_request
    end

    config.after do
      Bullet.perform_out_of_channel_notifications if Bullet.notification?
      Bullet.end_request
    end
  end
```

config/environments/test.rb
``` ruby
  config.after_initialize do
    Bullet.enable = true
    Bullet.bullet_logger = true
    Bullet.raise = true # raise an error if n+1 query occurs
  end
```

```
An error occurred while loading ./spec/requests/xxx_spec.rb.
Failure/Error: if Bullet.enable?

NameError:
  uninitialized constant Bullet
# ./spec/spec_helper.rb:104:in `block in <top (required)>'
# ./spec/spec_helper.rb:25:in `<top (required)>'
# ./spec/rails_helper.rb:4:in `require'
# ./spec/rails_helper.rb:4:in `<top (required)>'
```

**Comment by dim0627** [comment]
I'm so sorry.
I moved to rails_helper.rb from spec_helper.rb then fixed this problem.
