### ISSUE TITLE
Bullet raises the error on a Grape API endpoint with status: :no_content (204)

### ISSUE THREAD

**Issue by manme** [flyerhzm/bullet#512]
The error: 
```
 undefined method `empty?' for 204:Integer excluded from capture: No host specified, no public_key specified, no project_id specified
app                 |
app                 | NoMethodError (undefined method `empty?' for 204:Integer):
app                 |
app                 | bullet (6.1.0) lib/bullet/rack.rb:44:in `empty?'
app                 | bullet (6.1.0) lib/bullet/rack.rb:20:in `call'
```

The response is done in the Grape api: 
```
status :no_content
```

Seems bullet can't handle the empty response correctly

**Comment by magneland** [comment]
May I ask how you configure bullet with Grape API? I'm using a standard config, but I'm not sure whether it actually is enabled for Grape API calls.

**Comment by manme** [comment]
My config in development env file:
```
config.after_initialize do
     Bullet.enable = true
     Bullet.bullet_logger = true
   end
```
and the described error is raised even when 
```
 Bullet.enable = false 
```

**Comment by davidauza-engineer** [comment]
I'm having the exact same issue

**Comment by davidauza-engineer** [comment]
Is there a way to turn off bullet for Grape as a workaround?

**Comment by davidauza-engineer** [comment]
What worked for me was setting 

```ruby
Bullet.enable = false
```

That way the error wasn't displayed anymore. But this is something that definitely needs to be fixed

**Comment by flyerhzm** [comment]
I didn't use `grape`, but bullet works for `rails` 204 response.

maybe you can hack `lib/bullet/rack.rb` and see what's wrong.

**Comment by iansrc0811** [comment]
I encounter this bug too and found how to reproduce this issue:
In a Grape API endpoint, write a query with an n+1 issue to trigger Bullet check and return 204 status, and there it shows.
Solve the n+1 query issue to bypass this bug
Yes, this bug needs to be fixed but you can prevent it.
