### ISSUE TITLE
sentry-ruby is not supported

### ISSUE THREAD

**Issue by cxspxr** [flyerhzm/bullet#543]
I was using sentry-raven with bullet and it worked fine

Since it is advised by sentry to migrate to sentry-ruby, I was trying to do so, but received:
`NameError (uninitialized constant UniformNotifier::SentryNotifier::Raven)`

Raven class is no longer supported in a sentry-ruby SDK.

**Comment by cxspxr** [comment]
Also, beside that error, If I don't provide any sentry dsn to sentry-raven + bullet, it still works fine. With sentry-ruby it fails even before that error with: 
```
/home/casper/.rvm/gems/ruby-2.6.6/gems/sentry-rails-4.1.3/lib/sentry/rails/rescued_exception_interceptor.rb:12: warning: #<Class:Sentry>#configuration at /home/casper/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/forwardable.rb:158 forwarding to private method NilClass#configuration
  
NoMethodError (undefined method `configuration' for nil:NilClass):
  
/home/casper/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/forwardable.rb:228:in `configuration'
sentry-rails (4.1.3) lib/sentry/rails/rescued_exception_interceptor.rb:12:in `rescue in call'
sentry-rails (4.1.3) lib/sentry/rails/rescued_exception_interceptor.rb:8:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
remotipart (1.4.4) lib/remotipart/middleware.rb:32:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/cookies.rb:648:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
activerecord (6.0.3.4) lib/active_record/migration.rb:567:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.4) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack-contrib (2.1.0) lib/rack/contrib/response_headers.rb:17:in `call'
meta_request (0.7.2) lib/meta_request/middlewares/headers.rb:16:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
railties (6.0.3.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.4) lib/rails/rack/logger.rb:26:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/request_id.rb:27:in `call'
skylight-core (4.3.2) lib/skylight/core/probes/action_dispatch/request_id.rb:12:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rails_autoscale_agent (0.10.1) lib/rails_autoscale_agent/middleware.rb:27:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
activesupport (6.0.3.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack-livereload (0.3.17) lib/rack/livereload.rb:23:in `_call'
rack-livereload (0.3.17) lib/rack/livereload.rb:14:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/static.rb:126:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
sentry-ruby (4.1.3) lib/sentry/rack/capture_exceptions.rb:9:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack-mini-profiler (2.3.0) lib/mini_profiler/profiler.rb:373:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
webpacker (5.2.1) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
railties (6.0.3.4) lib/rails/engine.rb:527:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
puma (5.1.1) lib/puma/configuration.rb:246:in `call'
puma (5.1.1) lib/puma/request.rb:76:in `block in handle_request'
puma (5.1.1) lib/puma/thread_pool.rb:337:in `with_force_shutdown'
puma (5.1.1) lib/puma/request.rb:75:in `handle_request'
puma (5.1.1) lib/puma/server.rb:431:in `process_client'
puma (5.1.1) lib/puma/thread_pool.rb:145:in `block in spawn_thread'
```
