### ISSUE TITLE
wrong detecting HABTM association name when checking N+1

### ISSUE THREAD

**Issue by senid231** [flyerhzm/bullet#546]
When preloading HABTM association to model with bullet check - bullet raise error that association is not being included (but in logs I see that it being loaded only once so no N+1 problem in this case), but name of the assoication is wrong - it is singular, but must be plural.

Here's bug report that reproduces the issue:

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', ENV.fetch('RAILS_VERSION', '~> 6.0')
  gem 'sqlite3'

  if ENV['BULLET_VERSION']
    gem 'bullet', ENV['BULLET_VERSION'], require: false
  else
    gem 'bullet', require: false
  end
end

require 'active_record'
require 'minitest/autorun'
require 'logger'
require 'bullet'
require 'bullet/version'

STDOUT.puts "\n\nBULLET VERSION #{Bullet::VERSION}"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)
Rails.logger = ActiveRecord::Base.logger

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title, null: false
    t.string :content
  end

  create_table :authors, force: true do |t|
    t.string :full_name, null: false
  end

  create_table :posts_authors, force: true do |t|
    t.references :post, null: false
    t.references :author, null: false
  end
end

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class Post < ApplicationRecord
  has_and_belongs_to_many :authors,
                          class_name: 'Author',
                          join_table: :posts_authors,
                          association_foreign_key: :author_id,
                          foreign_key: :post_id

  validates :authors, presence: true
end

class Author < ApplicationRecord
  has_and_belongs_to_many :posts,
                          class_name: 'Post',
                          join_table: :posts_authors,
                          association_foreign_key: :post_id,
                          foreign_key: :author_id
end

class BugTest < Minitest::Test
  def test_association_stuff
    author_1 = Author.create!(full_name: 'author 1')
    author_2 = Author.create!(full_name: 'author 2')
    author_3 = Author.create!(full_name: 'author 3')
    Post.create! title: 'post 1', authors: [author_1]
    Post.create! title: 'post 2', authors: [author_2, author_3]

    with_bullet(:n) do
      scope = Post.preload(:authors)
      records = scope.to_a
      assert_equal(2, records.size)
      records.each { |record| assert record.association(:authors).loaded? }
      records.each { |record| record.authors.to_a } # emulate usage
    end
  end

  private

  def with_bullet(*checks)
    checks = [:n, :u, :c] if checks.empty?
    Bullet.enable = true
    Bullet.rails_logger = true
    Bullet.raise = true
    Bullet.n_plus_one_query_enable = checks.include?(:n)
    Bullet.unused_eager_loading_enable = checks.include?(:u)
    Bullet.counter_cache_enable = checks.include?(:c)

    Bullet.start_request
    yield
  ensure
    Bullet.perform_out_of_channel_notifications if Bullet.notification?
    Bullet.end_request

    Bullet.enable = false
  end
end
```

Output of this bug report with bullet 6.1.3
```
Fetching gem metadata from https://rubygems.org/.............
Resolving dependencies...
Using rake 13.0.3
Using concurrent-ruby 1.1.8
Using minitest 5.14.3
Using zeitwerk 2.4.2
Using builder 3.2.4
Using erubi 1.10.0
Using racc 1.5.2
Using crass 1.0.6
Using rack 2.2.3
Using nio4r 2.5.4
Using websocket-extensions 0.1.5
Using mimemagic 0.3.5
Using mini_mime 1.0.2
Using uniform_notifier 1.13.2
Using bundler 2.2.8
Using method_source 1.0.0
Using sqlite3 1.4.2
Using i18n 1.8.8
Using tzinfo 2.0.4
Using nokogiri 1.11.1 (x86_64-linux)
Using rack-test 1.1.0
Using websocket-driver 0.7.3
Using marcel 0.3.3
Using sprockets 4.0.2
Using thor 1.1.0
Using mail 2.7.1
Using activesupport 6.1.1
Using loofah 2.9.0
Using rails-html-sanitizer 1.3.0
Using globalid 0.4.2
Using activemodel 6.1.1
Using rails-dom-testing 2.0.3
Using activerecord 6.1.1
Using actionview 6.1.1
Using activejob 6.1.1
Using bullet 6.1.3
Using actionpack 6.1.1
Using actioncable 6.1.1
Using activestorage 6.1.1
Using actionmailer 6.1.1
Using railties 6.1.1
Using sprockets-rails 3.2.2
Using actionmailbox 6.1.1
Using actiontext 6.1.1
Using rails 6.1.1
BULLET VERSION 6.1.3
-- create_table(:posts, {:force=>true})
D, [2021-02-04T12:13:37.001335 #2649861] DEBUG -- :    (0.5ms)  SELECT sqlite_version(*)
D, [2021-02-04T12:13:37.001606 #2649861] DEBUG -- :    (0.0ms)  DROP TABLE IF EXISTS "posts"
D, [2021-02-04T12:13:37.001861 #2649861] DEBUG -- :    (0.1ms)  CREATE TABLE "posts" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar NOT NULL, "content" varchar)
   -> 0.0028s
-- create_table(:authors, {:force=>true})
D, [2021-02-04T12:13:37.002041 #2649861] DEBUG -- :    (0.0ms)  DROP TABLE IF EXISTS "authors"
D, [2021-02-04T12:13:37.002236 #2649861] DEBUG -- :    (0.1ms)  CREATE TABLE "authors" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "full_name" varchar NOT NULL)
   -> 0.0004s
-- create_table(:posts_authors, {:force=>true})
D, [2021-02-04T12:13:37.002427 #2649861] DEBUG -- :    (0.0ms)  DROP TABLE IF EXISTS "posts_authors"
D, [2021-02-04T12:13:37.002594 #2649861] DEBUG -- :    (0.1ms)  CREATE TABLE "posts_authors" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "post_id" integer NOT NULL, "author_id" integer NOT NULL)
D, [2021-02-04T12:13:37.012754 #2649861] DEBUG -- :    (10.0ms)  CREATE INDEX "index_posts_authors_on_post_id" ON "posts_authors" ("post_id")
D, [2021-02-04T12:13:37.013749 #2649861] DEBUG -- :    (0.6ms)  CREATE INDEX "index_posts_authors_on_author_id" ON "posts_authors" ("author_id")
   -> 0.0115s
D, [2021-02-04T12:13:37.036237 #2649861] DEBUG -- :    (0.1ms)  CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL)
D, [2021-02-04T12:13:37.041962 #2649861] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.1ms)  SELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? LIMIT ?  [["key", "environment"], ["LIMIT", 1]]
D, [2021-02-04T12:13:37.044765 #2649861] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2021-02-04T12:13:37.044945 #2649861] DEBUG -- :   ActiveRecord::InternalMetadata Create (0.1ms)  INSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["key", "environment"], ["value", "development"], ["created_at", "2021-02-04 10:13:37.044493"], ["updated_at", "2021-02-04 10:13:37.044493"]]
D, [2021-02-04T12:13:37.045079 #2649861] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
D, [2021-02-04T12:13:37.100088 #2649861] DEBUG -- :   TRANSACTION (0.1ms)  begin transaction
D, [2021-02-04T12:13:37.100242 #2649861] DEBUG -- :   Author Create (0.1ms)  INSERT INTO "authors" ("full_name") VALUES (?)  [["full_name", "author 1"]]
D, [2021-02-04T12:13:37.100404 #2649861] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
D, [2021-02-04T12:13:37.100744 #2649861] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2021-02-04T12:13:37.100862 #2649861] DEBUG -- :   Author Create (0.1ms)  INSERT INTO "authors" ("full_name") VALUES (?)  [["full_name", "author 2"]]
D, [2021-02-04T12:13:37.100980 #2649861] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
D, [2021-02-04T12:13:37.101267 #2649861] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2021-02-04T12:13:37.101385 #2649861] DEBUG -- :   Author Create (0.1ms)  INSERT INTO "authors" ("full_name") VALUES (?)  [["full_name", "author 3"]]
D, [2021-02-04T12:13:37.101495 #2649861] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
D, [2021-02-04T12:13:37.115089 #2649861] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2021-02-04T12:13:37.115228 #2649861] DEBUG -- :   Post Create (0.1ms)  INSERT INTO "posts" ("title") VALUES (?)  [["title", "post 1"]]
D, [2021-02-04T12:13:37.115650 #2649861] DEBUG -- :   Post::HABTM_Authors Create (0.1ms)  INSERT INTO "posts_authors" ("post_id", "author_id") VALUES (?, ?)  [["post_id", 1], ["author_id", 1]]
D, [2021-02-04T12:13:37.115823 #2649861] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
D, [2021-02-04T12:13:37.117171 #2649861] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2021-02-04T12:13:37.117290 #2649861] DEBUG -- :   Post Create (0.1ms)  INSERT INTO "posts" ("title") VALUES (?)  [["title", "post 2"]]
D, [2021-02-04T12:13:37.117639 #2649861] DEBUG -- :   Post::HABTM_Authors Create (0.1ms)  INSERT INTO "posts_authors" ("post_id", "author_id") VALUES (?, ?)  [["post_id", 2], ["author_id", 2]]
D, [2021-02-04T12:13:37.117939 #2649861] DEBUG -- :   Post::HABTM_Authors Create (0.1ms)  INSERT INTO "posts_authors" ("post_id", "author_id") VALUES (?, ?)  [["post_id", 2], ["author_id", 3]]
D, [2021-02-04T12:13:37.118108 #2649861] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
D, [2021-02-04T12:13:37.121834 #2649861] DEBUG -- :   Post Load (0.1ms)  SELECT "posts".* FROM "posts"
D, [2021-02-04T12:13:37.122566 #2649861] DEBUG -- :   HABTM_Authors Load (0.1ms)  SELECT "posts_authors".* FROM "posts_authors" WHERE "posts_authors"."post_id" IN (?, ?)  [[nil, 1], [nil, 2]]
D, [2021-02-04T12:13:37.123113 #2649861] DEBUG -- :   Author Load (0.1ms)  SELECT "authors".* FROM "authors" WHERE "authors"."id" IN (?, ?, ?)  [[nil, 1], [nil, 2], [nil, 3]]
W, [2021-02-04T12:13:37.124776 #2649861]  WARN -- : user: senid
 
USE eager loading detected
  Post::HABTM_Authors => [:author]
  Add to your query: .includes([:author])
Call stack
  test_bug_report_bullet.rb:83:in `block (2 levels) in test_association_stuff'
  test_bug_report_bullet.rb:83:in `each'
  test_bug_report_bullet.rb:83:in `block in test_association_stuff'
  test_bug_report_bullet.rb:108:in `with_bullet'
  test_bug_report_bullet.rb:78:in `test_association_stuff'

Minitest::UnexpectedError: Bullet::Notification::UnoptimizedQueryError: user: senid
 
USE eager loading detected
  Post::HABTM_Authors => [:author]
  Add to your query: .includes([:author])
Call stack
  test_bug_report_bullet.rb:83:in `block (2 levels) in test_association_stuff'
  test_bug_report_bullet.rb:83:in `each'
  test_bug_report_bullet.rb:83:in `block in test_association_stuff'
  test_bug_report_bullet.rb:108:in `with_bullet'
  test_bug_report_bullet.rb:78:in `test_association_stuff'

    .rvm/gems/ruby-2.5.5@tmp/gems/uniform_notifier-1.13.2/lib/uniform_notifier/raise.rb:18:in `_out_of_channel_notify'
    .rvm/gems/ruby-2.5.5@tmp/gems/uniform_notifier-1.13.2/lib/uniform_notifier/base.rb:24:in `out_of_channel_notify'
    .rvm/gems/ruby-2.5.5@tmp/gems/bullet-6.1.3/lib/bullet/notification/base.rb:50:in `notify_out_of_channel'
    .rvm/gems/ruby-2.5.5@tmp/gems/bullet-6.1.3/lib/bullet.rb:193:in `block in perform_out_of_channel_notifications'
    .rvm/gems/ruby-2.5.5@tmp/gems/bullet-6.1.3/lib/bullet.rb:255:in `block (2 levels) in for_each_active_notifier_with_notification'
    .rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/set.rb:338:in `each_key'
    .rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/set.rb:338:in `each'
    .rvm/gems/ruby-2.5.5@tmp/gems/bullet-6.1.3/lib/bullet.rb:253:in `block in for_each_active_notifier_with_notification'
    .rvm/gems/ruby-2.5.5@tmp/gems/bullet-6.1.3/lib/bullet.rb:252:in `each'
    .rvm/gems/ruby-2.5.5@tmp/gems/bullet-6.1.3/lib/bullet.rb:252:in `for_each_active_notifier_with_notification'
    .rvm/gems/ruby-2.5.5@tmp/gems/bullet-6.1.3/lib/bullet.rb:191:in `perform_out_of_channel_notifications'
    test_bug_report_bullet.rb:110:in `with_bullet'
    test_bug_report_bullet.rb:78:in `test_association_stuff'
.rvm/gems/ruby-2.5.5@tmp/gems/uniform_notifier-1.13.2/lib/uniform_notifier/raise.rb:18:in `_out_of_channel_notify'
.rvm/gems/ruby-2.5.5@tmp/gems/uniform_notifier-1.13.2/lib/uniform_notifier/base.rb:24:in `out_of_channel_notify'
.rvm/gems/ruby-2.5.5@tmp/gems/bullet-6.1.3/lib/bullet/notification/base.rb:50:in `notify_out_of_channel'
.rvm/gems/ruby-2.5.5@tmp/gems/bullet-6.1.3/lib/bullet.rb:193:in `block in perform_out_of_channel_notifications'
.rvm/gems/ruby-2.5.5@tmp/gems/bullet-6.1.3/lib/bullet.rb:255:in `block (2 levels) in for_each_active_notifier_with_notification'
.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/set.rb:338:in `each_key'
.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/set.rb:338:in `each'
.rvm/gems/ruby-2.5.5@tmp/gems/bullet-6.1.3/lib/bullet.rb:253:in `block in for_each_active_notifier_with_notification'
.rvm/gems/ruby-2.5.5@tmp/gems/bullet-6.1.3/lib/bullet.rb:252:in `each'
.rvm/gems/ruby-2.5.5@tmp/gems/bullet-6.1.3/lib/bullet.rb:252:in `for_each_active_notifier_with_notification'
.rvm/gems/ruby-2.5.5@tmp/gems/bullet-6.1.3/lib/bullet.rb:191:in `perform_out_of_channel_notifications'
test_bug_report_bullet.rb:110:in `with_bullet'
test_bug_report_bullet.rb:78:in `test_association_stuff'
```

**Comment by giapnhdev** [comment]
Got the same problem with `has_and_belongs_to_many` condition.

**Comment by tbro-evi** [comment]
(tested on version `6.1.4`)

@senid231 So I was experiencing this same issue and did a little bit of debugging. It looks like `bullet` does some inference to detect a join table model in [lib/bullet/detector/n_plus_one_query.rb](https://github.com/flyerhzm/bullet/blob/2c8a6d26f4a11bc8b3af5ff7da815401049732d4/lib/bullet/detector/n_plus_one_query.rb#L37) in that if a model/table doesn't have a primary key, it infers that it must be a join table (since they don't typically have primary key/id columns). So, in your example, if you used the following setup, your test would pass.

Also checkout this `Object` extension where `Bullet` grabs the primary_key(s) or id from the model: [lib/bullet/ext/object.rb](https://github.com/flyerhzm/bullet/blob/0d5b02ca303544a3dd39c208b6b962576c8e61d8/lib/bullet/ext/object.rb)

```
create_table :posts_authors, force: true, id: false do |t|
    t.references :post, null: false
    t.references :author, null: false
end

# OR

create_join_table :posts, :authors, force: true do |t| # this automatically passes in id: false
    t.references :post, null: false
    t.references :author, null: false
end
```

**Comment by tbro-evi** [comment]
Ah, ok. So after a little bit more digging, I found [that this line in /lib/bullet/detector/n_plus_one_query.rb#L37](https://github.com/flyerhzm/bullet/blob/2c8a6d26f4a11bc8b3af5ff7da815401049732d4/lib/bullet/detector/n_plus_one_query.rb#L37) was added to early exit if the object was a new record in [this commit](https://github.com/flyerhzm/bullet/commit/deaaf4dee41816403b889cbea0a6488637b7f72c). So, I _believe_ the fix here is to not assume that lack of an `id` attribute means the object is new.
