### ISSUE TITLE
Wrong table name detection on HABTM eager_load

### ISSUE THREAD

**Issue by senid231** [flyerhzm/bullet#586]
## Summary
When eager load HABTM association and access it `bullet` fails and asks to add non-existing assocaition to eager load.

`RoutingPlan` has and belongs to many `RoutingGroup`
`RoutingGroup` has and belongs to many `RoutingPlan`

When we fetch collection as `RoutingPlan.eager_load(:routing_groups)` and try to access `routing_groups` for collection records `bullet N+1` check raises error:
```
USE eager loading detected
  RoutingPlan => [:routing_groups_routingplans]
  Add to your query: .includes([:routing_groups_routingplans])
```

## Bug Report code
```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', ENV.fetch('RAILS_VERSION', '~> 6.0')
  gem 'sqlite3'

  gem 'bullet', github: 'flyerhzm/bullet', require: false
  # if ENV['BULLET_VERSION']
  #   gem 'bullet', ENV['BULLET_VERSION'], require: false
  # else
  #   gem 'bullet', require: false
  # end
end

require 'active_record'
require 'minitest/autorun'
require 'logger'
require 'bullet'
require 'bullet/version'

STDOUT.puts "\n\nBULLET VERSION #{Bullet::VERSION}"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)
Rails.logger = ActiveRecord::Base.logger

ActiveRecord::Schema.define do
  create_table :routing_groups, force: true do |t|
    t.string :name, null: false
  end

  create_table :routing_plans, force: true do |t|
    t.string :name, null: false
  end

  create_table :routing_plan_groups, force: true do |t|
    t.references :routing_group, null: false
    t.references :routing_plan, null: false
  end
end

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class RoutingPlan < ApplicationRecord
  self.table_name = 'routing_plans'
  has_and_belongs_to_many :routing_groups,
                          class_name: 'RoutingGroup',
                          join_table: 'routing_plan_groups'
end

class RoutingGroup < ApplicationRecord
  self.table_name = 'routing_groups'
  has_and_belongs_to_many :routing_plans,
                          class_name: 'RoutingPlan',
                          join_table: 'routing_plan_groups'
end

class BugTest < Minitest::Test
  def test_habtm_eager_load
    routing_plan_1 = RoutingPlan.create!(name: 'p 1')
    routing_plan_2 = RoutingPlan.create!(name: 'p 2')
    routing_plan_3 = RoutingPlan.create!(name: 'p 3')
    RoutingGroup.create! name: 'gr 1', routing_plans: [routing_plan_1]
    RoutingGroup.create! name: 'gr 2', routing_plans: [routing_plan_2, routing_plan_3]

    with_bullet(:n) do
      scope = RoutingPlan.eager_load(:routing_groups)
      records = scope.to_a
      assert_equal(3, records.size)
      records.each { |record| assert record.association(:routing_groups).loaded? }
      records.each { |record| record.routing_groups.to_a } # emulate usage
    end

    with_bullet(:n) do
      scope = RoutingGroup.eager_load(:routing_plans)
      records = scope.to_a
      assert_equal(2, records.size)
      records.each { |record| assert record.association(:routing_plans).loaded? }
      records.each { |record| record.routing_plans.to_a } # emulate usage
    end
  end

  private

  def with_bullet(*checks)
    checks = [:n, :u, :c] if checks.empty?
    Bullet.enable = true
    Bullet.rails_logger = true
    Bullet.raise = true
    Bullet.n_plus_one_query_enable = checks.include?(:n)
    Bullet.unused_eager_loading_enable = checks.include?(:u)
    Bullet.counter_cache_enable = checks.include?(:c)

    Bullet.start_request
    yield
  ensure
    Bullet.perform_out_of_channel_notifications if Bullet.notification?
    Bullet.end_request

    Bullet.enable = false
  end
end
```

## Bug Report output
```
Testing started at 15:58 ...
Fetching https://github.com/flyerhzm/bullet.git
Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 13.0.4
Using concurrent-ruby 1.1.9
Using minitest 5.14.4
Using zeitwerk 2.4.2
Using builder 3.2.4
Using erubi 1.10.0
Using mini_portile2 2.5.3
Using crass 1.0.6
Using rack 2.2.3
Using nio4r 2.5.7
Using websocket-extensions 0.1.5
Using marcel 1.0.1
Using mini_mime 1.1.0
Using uniform_notifier 1.14.2
Using bundler 1.17.3
Using method_source 1.0.0
Using thor 1.1.0
Using sqlite3 1.4.2
Using racc 1.5.2
Using tzinfo 2.0.4
Using i18n 1.8.10
Using rack-test 1.1.0
Using sprockets 4.0.2
Using websocket-driver 0.7.5
Using mail 2.7.1
Using activesupport 6.1.4
Using nokogiri 1.11.7 (x86_64-linux)
Using globalid 0.4.2
Using activemodel 6.1.4
Using bullet 6.1.4 from https://github.com/flyerhzm/bullet.git (at master@e44e375)
Using rails-dom-testing 2.0.3
Using loofah 2.10.0
Using rails-html-sanitizer 1.3.0
Using activejob 6.1.4
Using activerecord 6.1.4
Using actionview 6.1.4
Using actionpack 6.1.4
Using actioncable 6.1.4
Using activestorage 6.1.4
Using actionmailer 6.1.4
Using railties 6.1.4
Using sprockets-rails 3.2.2
Using actiontext 6.1.4
Using actionmailbox 6.1.4
Using rails 6.1.4


BULLET VERSION 6.1.4
-- create_table(:routing_groups, {:force=>true})
D, [2021-07-06T15:58:20.439352 #212076] DEBUG -- :    (0.4ms)  SELECT sqlite_version(*)
D, [2021-07-06T15:58:20.439550 #212076] DEBUG -- :    (0.0ms)  DROP TABLE IF EXISTS "routing_groups"
D, [2021-07-06T15:58:20.439737 #212076] DEBUG -- :    (0.1ms)  CREATE TABLE "routing_groups" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL)
   -> 0.0030s
-- create_table(:routing_plans, {:force=>true})
D, [2021-07-06T15:58:20.439870 #212076] DEBUG -- :    (0.0ms)  DROP TABLE IF EXISTS "routing_plans"
D, [2021-07-06T15:58:20.439983 #212076] DEBUG -- :    (0.1ms)  CREATE TABLE "routing_plans" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL)
   -> 0.0002s
-- create_table(:routing_plan_groups, {:force=>true})
D, [2021-07-06T15:58:20.440117 #212076] DEBUG -- :    (0.0ms)  DROP TABLE IF EXISTS "routing_plan_groups"
D, [2021-07-06T15:58:20.440234 #212076] DEBUG -- :    (0.1ms)  CREATE TABLE "routing_plan_groups" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "routing_group_id" integer NOT NULL, "routing_plan_id" integer NOT NULL)
D, [2021-07-06T15:58:20.440369 #212076] DEBUG -- :    (0.1ms)  CREATE INDEX "index_routing_plan_groups_on_routing_group_id" ON "routing_plan_groups" ("routing_group_id")
D, [2021-07-06T15:58:20.440480 #212076] DEBUG -- :    (0.1ms)  CREATE INDEX "index_routing_plan_groups_on_routing_plan_id" ON "routing_plan_groups" ("routing_plan_id")
   -> 0.0005s
D, [2021-07-06T15:58:20.452590 #212076] DEBUG -- :    (0.1ms)  CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL)
D, [2021-07-06T15:58:20.456448 #212076] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.1ms)  SELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? LIMIT ?  [["key", "environment"], ["LIMIT", 1]]
D, [2021-07-06T15:58:20.458750 #212076] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2021-07-06T15:58:20.458874 #212076] DEBUG -- :   ActiveRecord::InternalMetadata Create (0.0ms)  INSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["key", "environment"], ["value", "test"], ["created_at", "2021-07-06 12:58:20.458530"], ["updated_at", "2021-07-06 12:58:20.458530"]]
D, [2021-07-06T15:58:20.458962 #212076] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
D, [2021-07-06T15:58:20.487348 #212076] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2021-07-06T15:58:20.487457 #212076] DEBUG -- :   RoutingPlan Create (0.0ms)  INSERT INTO "routing_plans" ("name") VALUES (?)  [["name", "p 1"]]
D, [2021-07-06T15:58:20.487742 #212076] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
D, [2021-07-06T15:58:20.487939 #212076] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2021-07-06T15:58:20.488014 #212076] DEBUG -- :   RoutingPlan Create (0.0ms)  INSERT INTO "routing_plans" ("name") VALUES (?)  [["name", "p 2"]]
D, [2021-07-06T15:58:20.488085 #212076] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
D, [2021-07-06T15:58:20.488263 #212076] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2021-07-06T15:58:20.488533 #212076] DEBUG -- :   RoutingPlan Create (0.0ms)  INSERT INTO "routing_plans" ("name") VALUES (?)  [["name", "p 3"]]
D, [2021-07-06T15:58:20.488604 #212076] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
D, [2021-07-06T15:58:20.505670 #212076] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2021-07-06T15:58:20.505786 #212076] DEBUG -- :   RoutingGroup Create (0.1ms)  INSERT INTO "routing_groups" ("name") VALUES (?)  [["name", "gr 1"]]
D, [2021-07-06T15:58:20.506077 #212076] DEBUG -- :   RoutingGroup::HABTM_RoutingPlans Create (0.0ms)  INSERT INTO "routing_plan_groups" ("routing_group_id", "routing_plan_id") VALUES (?, ?)  [["routing_group_id", 1], ["routing_plan_id", 1]]
D, [2021-07-06T15:58:20.506198 #212076] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
D, [2021-07-06T15:58:20.507597 #212076] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2021-07-06T15:58:20.507682 #212076] DEBUG -- :   RoutingGroup Create (0.0ms)  INSERT INTO "routing_groups" ("name") VALUES (?)  [["name", "gr 2"]]
D, [2021-07-06T15:58:20.507930 #212076] DEBUG -- :   RoutingGroup::HABTM_RoutingPlans Create (0.0ms)  INSERT INTO "routing_plan_groups" ("routing_group_id", "routing_plan_id") VALUES (?, ?)  [["routing_group_id", 2], ["routing_plan_id", 2]]
D, [2021-07-06T15:58:20.508259 #212076] DEBUG -- :   RoutingGroup::HABTM_RoutingPlans Create (0.0ms)  INSERT INTO "routing_plan_groups" ("routing_group_id", "routing_plan_id") VALUES (?, ?)  [["routing_group_id", 2], ["routing_plan_id", 3]]
D, [2021-07-06T15:58:20.508381 #212076] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
D, [2021-07-06T15:58:20.513428 #212076] DEBUG -- :   SQL (0.1ms)  SELECT "routing_plans"."id" AS t0_r0, "routing_plans"."name" AS t0_r1, "routing_groups"."id" AS t1_r0, "routing_groups"."name" AS t1_r1 FROM "routing_plans" LEFT OUTER JOIN "routing_plan_groups" ON "routing_plan_groups"."routing_plan_id" = "routing_plans"."id" LEFT OUTER JOIN "routing_groups" ON "routing_groups"."id" = "routing_plan_groups"."routing_group_id"
W, [2021-07-06T15:58:20.515350 #212076]  WARN -- : user: senid
 
USE eager loading detected
  RoutingPlan => [:routing_groups_routingplans]
  Add to your query: .includes([:routing_groups_routingplans])
Call stack
  /home/senid/projects/bug_reports/test_bullet_habtm_2_bug_report.rb:79:in `block (2 levels) in test_habtm_eager_load'
  /home/senid/projects/bug_reports/test_bullet_habtm_2_bug_report.rb:79:in `each'
  /home/senid/projects/bug_reports/test_bullet_habtm_2_bug_report.rb:79:in `block in test_habtm_eager_load'
  /home/senid/projects/bug_reports/test_bullet_habtm_2_bug_report.rb:103:in `with_bullet'
  /home/senid/projects/bug_reports/test_bullet_habtm_2_bug_report.rb:74:in `test_habtm_eager_load'



Minitest::UnexpectedError: Bullet::Notification::UnoptimizedQueryError: user: senid
 
USE eager loading detected
  RoutingPlan => [:routing_groups_routingplans]
  Add to your query: .includes([:routing_groups_routingplans])
Call stack
  /home/senid/projects/bug_reports/test_bullet_habtm_2_bug_report.rb:79:in `block (2 levels) in test_habtm_eager_load'
  /home/senid/projects/bug_reports/test_bullet_habtm_2_bug_report.rb:79:in `each'
  /home/senid/projects/bug_reports/test_bullet_habtm_2_bug_report.rb:79:in `block in test_habtm_eager_load'
  /home/senid/projects/bug_reports/test_bullet_habtm_2_bug_report.rb:103:in `with_bullet'
  /home/senid/projects/bug_reports/test_bullet_habtm_2_bug_report.rb:74:in `test_habtm_eager_load'


    /home/senid/.rvm/gems/ruby-2.6.5@tmp/gems/uniform_notifier-1.14.2/lib/uniform_notifier/raise.rb:19:in `_out_of_channel_notify'
    /home/senid/.rvm/gems/ruby-2.6.5@tmp/gems/uniform_notifier-1.14.2/lib/uniform_notifier/base.rb:25:in `out_of_channel_notify'
    /home/senid/.rvm/gems/ruby-2.6.5@tmp/bundler/gems/bullet-e44e37512d78/lib/bullet/notification/base.rb:50:in `notify_out_of_channel'
    /home/senid/.rvm/gems/ruby-2.6.5@tmp/bundler/gems/bullet-e44e37512d78/lib/bullet.rb:192:in `block in perform_out_of_channel_notifications'
    /home/senid/.rvm/gems/ruby-2.6.5@tmp/bundler/gems/bullet-e44e37512d78/lib/bullet.rb:254:in `block (2 levels) in for_each_active_notifier_with_notification'
    /home/senid/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/set.rb:338:in `each_key'
    /home/senid/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/set.rb:338:in `each'
    /home/senid/.rvm/gems/ruby-2.6.5@tmp/bundler/gems/bullet-e44e37512d78/lib/bullet.rb:252:in `block in for_each_active_notifier_with_notification'
    /home/senid/.rvm/gems/ruby-2.6.5@tmp/bundler/gems/bullet-e44e37512d78/lib/bullet.rb:251:in `each'
    /home/senid/.rvm/gems/ruby-2.6.5@tmp/bundler/gems/bullet-e44e37512d78/lib/bullet.rb:251:in `for_each_active_notifier_with_notification'
    /home/senid/.rvm/gems/ruby-2.6.5@tmp/bundler/gems/bullet-e44e37512d78/lib/bullet.rb:190:in `perform_out_of_channel_notifications'
    /home/senid/projects/bug_reports/test_bullet_habtm_2_bug_report.rb:105:in `with_bullet'
    /home/senid/projects/bug_reports/test_bullet_habtm_2_bug_report.rb:74:in `test_habtm_eager_load'
/home/senid/.rvm/gems/ruby-2.6.5@tmp/gems/uniform_notifier-1.14.2/lib/uniform_notifier/raise.rb:19:in `_out_of_channel_notify'
/home/senid/.rvm/gems/ruby-2.6.5@tmp/gems/uniform_notifier-1.14.2/lib/uniform_notifier/base.rb:25:in `out_of_channel_notify'
/home/senid/.rvm/gems/ruby-2.6.5@tmp/bundler/gems/bullet-e44e37512d78/lib/bullet/notification/base.rb:50:in `notify_out_of_channel'
/home/senid/.rvm/gems/ruby-2.6.5@tmp/bundler/gems/bullet-e44e37512d78/lib/bullet.rb:192:in `block in perform_out_of_channel_notifications'
/home/senid/.rvm/gems/ruby-2.6.5@tmp/bundler/gems/bullet-e44e37512d78/lib/bullet.rb:254:in `block (2 levels) in for_each_active_notifier_with_notification'
/home/senid/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/set.rb:338:in `each_key'
/home/senid/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/set.rb:338:in `each'
/home/senid/.rvm/gems/ruby-2.6.5@tmp/bundler/gems/bullet-e44e37512d78/lib/bullet.rb:252:in `block in for_each_active_notifier_with_notification'
/home/senid/.rvm/gems/ruby-2.6.5@tmp/bundler/gems/bullet-e44e37512d78/lib/bullet.rb:251:in `each'
/home/senid/.rvm/gems/ruby-2.6.5@tmp/bundler/gems/bullet-e44e37512d78/lib/bullet.rb:251:in `for_each_active_notifier_with_notification'
/home/senid/.rvm/gems/ruby-2.6.5@tmp/bundler/gems/bullet-e44e37512d78/lib/bullet.rb:190:in `perform_out_of_channel_notifications'
/home/senid/projects/bug_reports/test_bullet_habtm_2_bug_report.rb:105:in `with_bullet'
/home/senid/projects/bug_reports/test_bullet_habtm_2_bug_report.rb:74:in `test_habtm_eager_load'

Process finished with exit code 1

```

**Comment by senid231** [comment]
looks like version 7.0.7 fixes the issue
