### ISSUE TITLE
Add support for Rails ActiveRecord 7.1.0

### ISSUE THREAD

**Issue by jkwuc89** [flyerhzm/bullet#676]
Rails 7.1.0 was released on 10/5/2023. When attempting to run Rails with version 7.0.7 of the bullet gem, the following occurs.
Please feel free to merge this issue with https://github.com/flyerhzm/bullet/issues/656 if appropriate.

```
bin/rails aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'bullet'.
Gem Load Error is: Bullet does not support active_record 7.1.0 yet
Backtrace for gem load error is:
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bullet-7.0.7/lib/bullet/dependency.rb:35:in `active_record_version'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bullet-7.0.7/lib/bullet.rb:14:in `<module:Bullet>'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bullet-7.0.7/lib/bullet.rb:11:in `<main>'
<internal:/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:60:in `block (2 levels) in require'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:55:in `each'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:55:in `block in require'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:44:in `each'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:44:in `require'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler.rb:187:in `require'
/Users/kwedinger/code/core/server/config/application.rb:12:in `<main>'
/Users/kwedinger/code/core/server/Rakefile:6:in `require_relative'
/Users/kwedinger/code/core/server/Rakefile:6:in `<main>'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0/lib/rails/commands/rake/rake_command.rb:43:in `block in with_rake'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0/lib/rails/command.rb:156:in `invoke_rake'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0/lib/rails/command.rb:73:in `block in invoke'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0/lib/rails/command.rb:149:in `with_argv'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0/lib/rails/command.rb:69:in `invoke'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0/lib/rails/commands.rb:18:in `<main>'
<internal:/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:6:in `<main>'
Bundler Error Backtrace:
/Users/kwedinger/code/core/server/config/application.rb:12:in `<main>'
/Users/kwedinger/code/core/server/Rakefile:6:in `require_relative'
/Users/kwedinger/code/core/server/Rakefile:6:in `<main>'
<internal:/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
bin/rails:6:in `<main>'

Caused by:
Bullet does not support active_record 7.1.0 yet
<internal:/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
/Users/kwedinger/code/core/server/config/application.rb:12:in `<main>'
/Users/kwedinger/code/core/server/Rakefile:6:in `require_relative'
/Users/kwedinger/code/core/server/Rakefile:6:in `<main>'
<internal:/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/Users/kwedinger/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
bin/rails:6:in `<main>'
(See full trace by running task with --trace)
```

**Comment by flyerhzm** [comment]
@jkwuc89 I just released bullet gem 7.1.0, which support rails 7.1.0.
